# Generated by Django 5.2.4 on 2025-12-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-visited_at'],
            },
        ),
    ]
