# Generated by Django 4.2.27 on 2026-01-15 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageVisit',
        ),
    ]
