# Generated by Django 5.2.4 on 2025-12-07 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BBSPost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False, verbose_name='投稿ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('content', models.TextField(verbose_name='本文')),
                ('comment_count', models.IntegerField(default=0, verbose_name='コメント数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bbs_post', to='reports.dailyreport', verbose_name='日報ID')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bbs_posts', to='stores.store', verbose_name='店舗ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bbs_posts', to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID')),
            ],
            options={
                'verbose_name': '掲示板投稿',
                'verbose_name_plural': '掲示板投稿',
                'db_table': 'bbs_posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BBSComment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False, verbose_name='コメントID')),
                ('content', models.TextField(verbose_name='本文')),
                ('is_best_answer', models.BooleanField(default=False, verbose_name='ベストアンサーフラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='bbs.bbspost', verbose_name='投稿ID')),
            ],
            options={
                'verbose_name': '掲示板コメント',
                'verbose_name_plural': '掲示板コメント',
                'db_table': 'bbs_comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='BBSReaction',
            fields=[
                ('reaction_id', models.AutoField(primary_key=True, serialize=False, verbose_name='リアクションID')),
                ('reaction_type', models.CharField(choices=[('naruhodo', 'なるほど'), ('soudane', 'そうだね'), ('arigatou', 'ありがとう')], max_length=20, verbose_name='リアクション種別')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='bbs.bbspost', verbose_name='投稿ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID')),
            ],
            options={
                'verbose_name': '掲示板リアクション',
                'verbose_name_plural': '掲示板リアクション',
                'db_table': 'bbs_reactions',
                'unique_together': {('post', 'user', 'reaction_type')},
            },
        ),
    ]
