# Generated by Django 6.0 on 2025-12-19 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BBSCommentReaction',
            fields=[
                ('reaction_id', models.AutoField(primary_key=True, serialize=False, verbose_name='リアクションID')),
                ('reaction_type', models.CharField(choices=[('naruhodo', 'なるほど'), ('soudane', 'そうだね'), ('arigatou', 'ありがとう')], max_length=20, verbose_name='リアクション種別')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='bbs.bbscomment', verbose_name='コメントID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_reactions', to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID')),
            ],
            options={
                'verbose_name': '掲示板コメントリアクション',
                'verbose_name_plural': '掲示板コメントリアクション',
                'db_table': 'bbs_comment_reactions',
                'unique_together': {('comment', 'user', 'reaction_type')},
            },
        ),
    ]
