# Generated by Django 6.0 on 2025-12-19 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbspost',
            name='genre',
            field=models.CharField(choices=[('claim', 'クレーム'), ('praise', '賞賛'), ('accident', '事故'), ('report', '報告'), ('other', 'その他')], default='report', max_length=20),
        ),
    ]
