# Generated by Django 5.2.6 on 2025-12-19 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0003_bbscommentreaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbscommentreaction',
            name='reaction_type',
            field=models.CharField(choices=[('naruhodo', 'なるほど'), ('iine', 'いいね')], max_length=20, verbose_name='リアクション種別'),
        ),
        migrations.AlterField(
            model_name='bbsreaction',
            name='reaction_type',
            field=models.CharField(choices=[('naruhodo', 'なるほど'), ('iine', 'いいね')], max_length=20, verbose_name='リアクション種別'),
        ),
    ]
