# Generated by Django 5.2.4 on 2025-12-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='ユーザーID')),
                ('user_type', models.CharField(choices=[('staff', 'スタッフ'), ('manager', '店長'), ('admin', '管理者')], default='staff', max_length=20, verbose_name='ユーザー種別')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='メールアドレス')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('login_at', models.DateTimeField(blank=True, null=True, verbose_name='ログイン時刻')),
                ('last_access_at', models.DateTimeField(blank=True, null=True, verbose_name='最終アクセス時刻')),
                ('is_active', models.BooleanField(default=True, verbose_name='アカウント有効フラグ')),
                ('is_staff', models.BooleanField(default=False, verbose_name='スタッフ権限')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'ユーザー',
                'verbose_name_plural': 'ユーザー',
                'db_table': 'users',
            },
        ),
    ]
