# Generated by Django 5.2.4 on 2025-12-07 13:32

import django.db.models.deletion
import reports.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False, verbose_name='日報ID')),
                ('date', models.DateField(verbose_name='日時')),
                ('genre', models.CharField(choices=[('claim', 'クレーム'), ('praise', '賞賛'), ('accident', '事故'), ('report', '報告'), ('other', 'その他')], max_length=20, verbose_name='ジャンル')),
                ('location', models.CharField(choices=[('kitchen', 'キッチン'), ('hall', 'ホール'), ('cashier', 'レジ'), ('toilet', 'トイレ'), ('other', 'その他')], max_length=20, verbose_name='場所')),
                ('title', models.CharField(max_length=200, verbose_name='件名')),
                ('content', models.TextField(verbose_name='内容')),
                ('post_to_bbs', models.BooleanField(default=False, verbose_name='掲示板連携フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='stores.store', verbose_name='店舗ID')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID')),
            ],
            options={
                'verbose_name': '日報',
                'verbose_name_plural': '日報',
                'db_table': 'daily_reports',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportImage',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False, verbose_name='画像ID')),
                ('file_path', models.ImageField(upload_to=reports.models.report_image_upload_path, verbose_name='ファイルパス')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='アップロード日時')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='reports.dailyreport', verbose_name='日報ID')),
            ],
            options={
                'verbose_name': '日報画像',
                'verbose_name_plural': '日報画像',
                'db_table': 'report_images',
            },
        ),
        migrations.CreateModel(
            name='StoreDailyPerformance',
            fields=[
                ('performance_id', models.AutoField(primary_key=True, serialize=False, verbose_name='実績ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('sales_amount', models.IntegerField(verbose_name='売上金額')),
                ('customer_count', models.IntegerField(verbose_name='客数')),
                ('cash_difference', models.IntegerField(default=0, verbose_name='違算金額')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_performances', to=settings.AUTH_USER_MODEL, verbose_name='登録者ユーザーID')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_performances', to='stores.store', verbose_name='店舗ID')),
            ],
            options={
                'verbose_name': '店舗日次実績',
                'verbose_name_plural': '店舗日次実績',
                'db_table': 'store_daily_performances',
                'ordering': ['-date'],
                'unique_together': {('store', 'date')},
            },
        ),
    ]
