# Generated by Django 5.2.4 on 2025-12-07 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysisResult',
            fields=[
                ('analysis_id', models.AutoField(primary_key=True, serialize=False, verbose_name='解析ID')),
                ('target_period', models.CharField(max_length=100, verbose_name='対象期間')),
                ('analysis_type', models.CharField(choices=[('daily', '日次分析'), ('weekly', '週次分析'), ('monthly', '月次分析'), ('custom', 'カスタム分析')], max_length=20, verbose_name='解析種別')),
                ('analysis_result', models.JSONField(verbose_name='解析結果')),
                ('warning_points', models.JSONField(verbose_name='以上箇所')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': 'AI分析結果',
                'verbose_name_plural': 'AI分析結果',
                'db_table': 'ai_analysis_results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIChatHistory',
            fields=[
                ('chat_id', models.AutoField(primary_key=True, serialize=False, verbose_name='チャットID')),
                ('role', models.CharField(choices=[('user', 'ユーザー'), ('assistant', 'AI')], max_length=20, verbose_name='役割')),
                ('message', models.TextField(verbose_name='メッセージ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_chats', to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID')),
            ],
            options={
                'verbose_name': 'AIチャット履歴',
                'verbose_name_plural': 'AIチャット履歴',
                'db_table': 'ai_chat_history',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIProposal',
            fields=[
                ('proposal_id', models.AutoField(primary_key=True, serialize=False, verbose_name='提案ID')),
                ('priority', models.IntegerField(choices=[(1, '低'), (2, '中'), (3, '高')], default=2, verbose_name='優先度')),
                ('proposal_type', models.CharField(choices=[('frequent_claim', '頻発するクレーム'), ('performance_decline', '自己評価の低下'), ('cash_difference', '違算の基準値超過'), ('other', 'その他')], max_length=50, verbose_name='種類')),
                ('content', models.TextField(verbose_name='提案内容')),
                ('is_read', models.BooleanField(default=False, verbose_name='既読')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_proposals', to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID')),
            ],
            options={
                'verbose_name': 'AI改善提案',
                'verbose_name_plural': 'AI改善提案',
                'db_table': 'ai_proposals',
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
