# Generated by Django 5.2.4 on 2025-12-16 11:11

import pgvector.django.vector
from django.contrib.postgres.operations import CreateExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_features', '0001_initial'),
    ]

    operations = [
        CreateExtension('vector'),
        migrations.CreateModel(
            name='DocumentVector',
            fields=[
                ('vector_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ベクトルID')),
                ('source_type', models.CharField(choices=[('daily_report', '日報'), ('bbs_post', '掲示板投稿'), ('bbs_comment', '掲示板コメント'), ('performance', '店舗実績')], db_index=True, max_length=20, verbose_name='ソース種別')),
                ('source_id', models.IntegerField(db_index=True, verbose_name='ソースID')),
                ('content', models.TextField(verbose_name='コンテンツ')),
                ('metadata', models.JSONField(default=dict, help_text='store_id, date, title などの追加情報', verbose_name='メタデータ')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=384, verbose_name='埋め込みベクトル')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'ドキュメントベクトル',
                'verbose_name_plural': 'ドキュメントベクトル',
                'db_table': 'document_vectors',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='AIAnalysisResult',
        ),
        migrations.RemoveField(
            model_name='aiproposal',
            name='user',
        ),
        migrations.AddIndex(
            model_name='documentvector',
            index=models.Index(fields=['source_type', 'source_id'], name='document_ve_source__cac594_idx'),
        ),
        migrations.AddIndex(
            model_name='documentvector',
            index=models.Index(fields=['created_at'], name='document_ve_created_90c49e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentvector',
            unique_together={('source_type', 'source_id')},
        ),
        migrations.DeleteModel(
            name='AIProposal',
        ),
    ]
