# Generated by Django 5.2.4 on 2025-12-10 14:39

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_features', '0001_initial'),
    ]

    operations = [
        # pgvector拡張を有効化
        migrations.RunSQL(
            sql="CREATE EXTENSION IF NOT EXISTS vector;",
            reverse_sql="DROP EXTENSION IF EXISTS vector CASCADE;",
        ),
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ドキュメントID')),
                ('document_type', models.CharField(choices=[('manual', 'マニュアル'), ('guideline', 'ガイドライン'), ('faq', 'FAQ'), ('policy', 'ポリシー')], max_length=20, verbose_name='ドキュメント種別')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('category', models.CharField(choices=[('hygiene', '衛生管理'), ('service', '接客'), ('cooking', '調理'), ('safety', '安全管理'), ('other', 'その他')], max_length=20, verbose_name='カテゴリ')),
                ('file_path', models.FileField(upload_to='knowledge/', verbose_name='ファイルパス')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word'), ('md', 'Markdown')], max_length=10, verbose_name='ファイル種別')),
                ('version', models.CharField(max_length=50, verbose_name='バージョン')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='作成者')),
                ('published_date', models.DateField(blank=True, null=True, verbose_name='公開日')),
                ('vectorized', models.BooleanField(default=False, verbose_name='ベクトル化済み')),
                ('vectorized_at', models.DateTimeField(blank=True, null=True, verbose_name='ベクトル化日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'ナレッジドキュメント',
                'verbose_name_plural': 'ナレッジドキュメント',
                'db_table': 'knowledge_documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVector',
            fields=[
                ('vector_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ベクトルID')),
                ('source_type', models.CharField(choices=[('daily_report', '日報'), ('bbs_post', '掲示板投稿'), ('bbs_comment', '掲示板コメント'), ('performance', '店舗実績')], db_index=True, max_length=20, verbose_name='ソース種別')),
                ('source_id', models.IntegerField(db_index=True, verbose_name='ソースID')),
                ('content', models.TextField(verbose_name='コンテンツ')),
                ('metadata', models.JSONField(default=dict, help_text='store_id, user_id, date, title などの追加情報', verbose_name='メタデータ')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=384, verbose_name='埋め込みベクトル')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'ドキュメントベクトル',
                'verbose_name_plural': 'ドキュメントベクトル',
                'db_table': 'document_vectors',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source_type', 'source_id'], name='document_ve_source__cac594_idx'), models.Index(fields=['created_at'], name='document_ve_created_90c49e_idx')],
                'unique_together': {('source_type', 'source_id')},
            },
        ),
        migrations.CreateModel(
            name='KnowledgeVector',
            fields=[
                ('vector_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ベクトルID')),
                ('document_type', models.CharField(choices=[('manual', 'マニュアル'), ('guideline', 'ガイドライン'), ('faq', 'FAQ'), ('policy', 'ポリシー')], db_index=True, max_length=20, verbose_name='ドキュメント種別')),
                ('content', models.TextField(verbose_name='チャンクコンテンツ')),
                ('metadata', models.JSONField(default=dict, help_text='category, document_title, chapter, section, version などの情報', verbose_name='メタデータ')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=384, verbose_name='埋め込みベクトル')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vectors', to='ai_features.knowledgedocument', verbose_name='元ドキュメント')),
            ],
            options={
                'verbose_name': 'ナレッジベクトル',
                'verbose_name_plural': 'ナレッジベクトル',
                'db_table': 'knowledge_vectors',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['document_type'], name='knowledge_v_documen_189223_idx'), models.Index(fields=['created_at'], name='knowledge_v_created_a68ffe_idx')],
            },
        ),
    ]
