# Generated by Django 5.2.4 on 2025-12-17 12:21

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_features', '0002_documentvector_delete_aianalysisresult_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeVector',
            fields=[
                ('vector_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ベクトルID')),
                ('document_type', models.CharField(choices=[('manual', 'マニュアル'), ('faq', 'FAQ'), ('policy', 'ポリシー'), ('guide', 'ガイド'), ('other', 'その他')], db_index=True, max_length=20, verbose_name='ドキュメント種別')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('content', models.TextField(verbose_name='コンテンツ')),
                ('metadata', models.JSONField(default=dict, help_text='category, tags, author などの追加情報', verbose_name='メタデータ')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=384, verbose_name='埋め込みベクトル')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'ナレッジベクトル',
                'verbose_name_plural': 'ナレッジベクトル',
                'db_table': 'knowledge_vectors',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['document_type'], name='knowledge_v_documen_189223_idx'), models.Index(fields=['created_at'], name='knowledge_v_created_a68ffe_idx')],
            },
        ),
    ]
