# Generated by Django 5.2.4 on 2025-12-07 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.AutoField(primary_key=True, serialize=False, verbose_name='店舗ID')),
                ('store_name', models.CharField(max_length=100, verbose_name='店舗名')),
                ('address', models.CharField(max_length=255, verbose_name='住所')),
                ('sales_target', models.CharField(blank=True, max_length=255, verbose_name='売り上げ目標')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_stores', to=settings.AUTH_USER_MODEL, verbose_name='管理者ユーザーID')),
            ],
            options={
                'verbose_name': '店舗',
                'verbose_name_plural': '店舗',
                'db_table': 'stores',
            },
        ),
    ]
