# Generated by Django 5.2.4 on 2025-12-13 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyGoal',
            fields=[
                ('goal_id', models.AutoField(primary_key=True, serialize=False, verbose_name='目標ID')),
                ('year', models.IntegerField(verbose_name='年')),
                ('month', models.IntegerField(verbose_name='月')),
                ('goal_text', models.TextField(verbose_name='目標内容')),
                ('achievement_rate', models.IntegerField(default=0, verbose_name='達成率（%）')),
                ('achievement_text', models.TextField(blank=True, verbose_name='達成状況')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_goals', to='stores.store', verbose_name='店舗ID')),
            ],
            options={
                'verbose_name': '月次目標',
                'verbose_name_plural': '月次目標',
                'db_table': 'monthly_goals',
                'ordering': ['-year', '-month'],
                'unique_together': {('store', 'year', 'month')},
            },
        ),
    ]
