# Generated by Django 5.2.4 on 2025-12-13 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_monthlygoal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='sales_target',
        ),
    ]
